name: Flake8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.9", "3.10.0-rc.2"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]
        then
          pip install -r requirements.txt
          pip install pytest hypothesis mypy
        fi
        if [ -f Pipfile ]
        then
          pip install pipenv
          pipenv update --dev
        fi
    - name: Lint with flake8
      timeout-minutes: 5
      run: |
        if [ -f Pipfile ]
        then
          pipenv run flake8 src tests
        else
          flake8 src test
        fi
