name: Pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]
        then
          pip install -r requirements.txt
          pip install pytest hypothesis mypy
        fi
        if [ -f Pipfile ]
        then
          pip install pipenv
          pipenv lock
          pipenv install --dev
        fi
    - name: Test with pytest
      timeout-minutes: 10
      run: |
        if [ -f Pipfile ]
        then
          pipenv run pytest
        else
          pytest
        fi
